// <auto-generated />
namespace Linqua.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddLanguageCodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLanguageCodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201509010637499_AddLanguageCodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
