// <auto-generated />
namespace Linqua.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddTranslationState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTranslationState));
        
        string IMigrationMetadata.Id
        {
            get { return "201507251047248_AddTranslationState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
