// <auto-generated />
namespace Linqua.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameUserIdToClientAppSpecificUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameUserIdToClientAppSpecificUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201606201843235_RenameUserIdToClientAppSpecificUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
